### ISSUE TITLE
Always shows "Passed"

### ISSUE THREAD

**Issue by Fabian1976** [AleksaC/hadolint-py#7]
I have added this to my .pre-commit file:
```
  - repo: 'https://github.com/AleksaC/hadolint-py'
    rev: 'v2.12.0'
    hooks:
      - id:   'hadolint'
        #args: [--ignore, DL3025, --ignore, DL3018]
```

When i run pre-commit, is shows Passed:
![image](https://github.com/AleksaC/hadolint-py/assets/9444852/f460d09a-d690-4949-9d41-094737359086)

But when i run hadolint by hand, it displays a warning:
```
$ hadolint Dockerfile                                                                                                                                                                      (precommit)
Dockerfile:3 DL3028 warning: Pin versions in gem install. Instead of `gem install <gem>` use `gem install <gem>:<version>`
```

So this doesn't seem to work. Or i'm doing something wrong.

**Comment by Fabian1976** [comment]
I have tried the version from this [PR](https://github.com/AleksaC/hadolint-py/pull/6), and is seems related.

**Comment by AleksaC** [comment]
Cannot reproduce this. 

`.pre-comit-config.yaml` :
```yaml
repos:
  - repo: 'https://github.com/AleksaC/hadolint-py'
    rev: 'v2.12.0.3'
    hooks:
      - id: 'hadolint'
```

`Dockerfile`:
```Dockerfile
FROM debian:bookworm
RUN gem install test
```

Output:
```console
Hadolint.................................................................Failed
- hook id: hadolint
- exit code: 1

Dockerfile:2 DL3028 warning: Pin versions in gem install. Instead of `gem install <gem>` use `gem install <gem>:<version>`
```

Had to use `'v2.12.0.3'` since your version doesn't work on apple silicone, you should consider updating to this version as well.

---

This should not be related to the PR you mentioned.

Is it possible that the dockerfile you're running this on is unstaged? In that case `pre-commit` would skip it, but still pass if there are other dockerfiles.

What version of pre-commit are you using?

**Comment by Fabian1976** [comment]
Version `v2.12.0.3` also didn't work.

I'm using this version now:
```
  - repo: 'https://github.com/zaro0508/hadolint-py'
    rev:  'v9.9.11'
    hooks:
      - id: 'hadolint'
```

And it does give the expected output when not specifying a version.
